import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Search, MapPin, Zap, ExternalLink, Phone, Globe, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { SiWhatsapp } from "react-icons/si";
import { geminiGenerate } from "@/lib/gemini";
const CITIES = ["Lahore", "Karachi", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Quetta"];

interface Lead {
  id: string;
  name: string;
  address: string;
  phone: string;
  website?: string;
  badge: "Hot" | "Warm" | "Cold";
  score: number;
  reason: string;
}

export default function ClientHunter() {
  const [skills, setSkills] = useState("");
  const [city, setCity] = useState("Lahore");
  const [clientType, setClientType] = useState("");
  const [userType, setUserType] = useState("Freelancer");
  const [isLoading, setIsLoading] = useState(false);
  const [results, setResults] = useState<Lead[] | null>(null);
  const [savedLeads, setSavedLeads] = useState<Set<string>>(new Set());

  useEffect(() => {
    document.title = "Client Hunter - Find Clients in Pakistan | FreelanceGuru AI";
    const saved = localStorage.getItem("savedLeads");
    if (saved) setSavedLeads(new Set(JSON.parse(saved)));
  }, []);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!clientType.trim()) {
      toast.error("Please enter a client type to search.");
      return;
    }

    setIsLoading(true);
    setResults(null);

    const prompt = `You are a business lead generator for Pakistani freelancers. Generate exactly 9 realistic business leads for a ${userType.toLowerCase()} offering "${skills || "freelance services"}" skills.

City: ${city}, Pakistan
Target businesses: ${clientType}

Return ONLY a valid JSON array with exactly 9 objects. No markdown, no explanation, just the JSON array. Each object must have these exact fields:
{
  "name": "Real-sounding Pakistani business name",
  "address": "Specific real street/area address in ${city}",
  "phone": "03XX-XXXXXXX format Pakistani mobile number",
  "website": "website.pk or null if none",
  "badge": "Hot" or "Warm" or "Cold",
  "score": number between 60-98,
  "reason": "One sentence why this is a good lead"
}

Rules:
- 3 must be "Hot" (score 80-98), 3 "Warm" (score 60-79), 3 "Cold" (score 40-65)
- Names should sound like real Pakistani businesses (use Urdu words, owner names, or industry terms)
- Addresses must be real areas/streets in ${city} (e.g. Gulberg, DHA, Johar Town for Lahore)
- Phone numbers: 03XX-XXXXXXX format (0300-0321-0333-0345 etc.)
- Websites use .pk, .com.pk, or .com (or null)
- Reason should relate to why "${skills || "a freelancer"}" would benefit this business`;

    try {
      const raw = await geminiGenerate(prompt, 0.8);
      const jsonMatch = raw.match(/\[[\s\S]*\]/);
      if (!jsonMatch) throw new Error("No JSON array found in response");

      const parsed: Omit<Lead, "id">[] = JSON.parse(jsonMatch[0]);
      const leads: Lead[] = parsed.map((l, i) => ({ ...l, id: `lead-${i}-${Date.now()}` }));

      setResults(leads);
      toast.success(`Found ${leads.length} AI-generated leads in ${city}!`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error("[ClientHunter] Error:", msg, err);
      toast.error(`Failed to generate leads: ${msg}`);
      setResults([]);
    } finally {
      setIsLoading(false);
    }
  };

  const toggleSave = (id: string, name: string) => {
    const next = new Set(savedLeads);
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
      toast.success(`"${name}" saved!`);
    }
    setSavedLeads(next);
    localStorage.setItem("savedLeads", JSON.stringify(Array.from(next)));
  };

  const badgeStyles: Record<string, string> = {
    Hot: "bg-red-500/20 text-red-400 border-red-500/50",
    Warm: "bg-orange-500/20 text-orange-400 border-orange-500/50",
    Cold: "bg-blue-500/20 text-blue-400 border-blue-500/50",
  };

  const scoreColor: Record<string, string> = {
    Hot: "#ef4444",
    Warm: "#f97316",
    Cold: "#3b82f6",
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="container mx-auto px-4 py-12 max-w-6xl"
    >
      <div className="text-center mb-12">
        <motion.h1
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-4xl md:text-5xl font-black mb-4"
        >
          Find the Best Clients in Your City
        </motion.h1>
        <p className="text-xl text-muted-foreground flex items-center justify-center gap-2">
          <Sparkles className="w-5 h-5 text-primary" />
          AI-powered leads generated by Google Gemini
        </p>
      </div>

      <div className="grid lg:grid-cols-12 gap-8">
        {/* Form */}
        <div className="lg:col-span-4">
          <div className="glass-card p-6 rounded-2xl sticky top-24">
            <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
              <Search className="w-5 h-5 text-primary" /> Search Filters
            </h3>
            <form onSubmit={handleSearch} className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Your Skills</label>
                <input
                  type="text"
                  placeholder="e.g. Web Development, SEO"
                  className="w-full bg-input border border-border rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary outline-none transition-all"
                  value={skills}
                  onChange={(e) => setSkills(e.target.value)}
                  data-testid="input-skills"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">City</label>
                <select
                  className="w-full bg-input border border-border rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary outline-none transition-all appearance-none"
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  data-testid="select-city"
                >
                  {CITIES.map((c) => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  Client Type <span className="text-destructive">*</span>
                </label>
                <input
                  type="text"
                  placeholder="e.g. restaurants, law firms, clinics"
                  className="w-full bg-input border border-border rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary outline-none transition-all"
                  value={clientType}
                  onChange={(e) => setClientType(e.target.value)}
                  required
                  data-testid="input-client-type"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">You are a</label>
                <div className="flex gap-4">
                  {["Freelancer", "Business"].map((type) => (
                    <label key={type} className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        checked={userType === type}
                        onChange={() => setUserType(type)}
                        className="text-primary focus:ring-primary"
                      />
                      {type}
                    </label>
                  ))}
                </div>
              </div>

              <motion.button
                type="submit"
                disabled={isLoading}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.97 }}
                className="w-full mt-6 py-3 rounded-xl font-bold text-white gradient-bg hover:glow-primary transition-all disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                data-testid="button-hunt-clients"
              >
                {isLoading ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    AI is hunting leads...
                  </>
                ) : (
                  <>
                    <Zap className="w-5 h-5" /> Hunt Clients Now
                  </>
                )}
              </motion.button>
            </form>
          </div>
        </div>

        {/* Results */}
        <div className="lg:col-span-8">
          {/* Skeleton */}
          {isLoading && (
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground flex items-center gap-2 mb-4">
                <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                Gemini AI is generating realistic leads for {city}...
              </p>
              <div className="grid md:grid-cols-2 gap-4">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="glass-card p-6 rounded-xl animate-pulse">
                    <div className="h-5 bg-white/10 rounded w-3/4 mb-3" />
                    <div className="h-3 bg-white/10 rounded w-full mb-2" />
                    <div className="h-3 bg-white/10 rounded w-2/3 mb-2" />
                    <div className="h-3 bg-white/10 rounded w-1/2 mb-5" />
                    <div className="h-1.5 bg-white/10 rounded-full mb-5" />
                    <div className="flex gap-2">
                      <div className="h-9 bg-white/10 rounded flex-1" />
                      <div className="h-9 bg-white/10 rounded flex-1" />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Empty */}
          {!isLoading && results && results.length === 0 && (
            <div className="glass-card p-12 rounded-2xl text-center">
              <Search className="w-12 h-12 text-muted-foreground mx-auto mb-4 opacity-50" />
              <h3 className="text-xl font-bold mb-2">No leads generated</h3>
              <p className="text-muted-foreground">Try different keywords or check your connection.</p>
            </div>
          )}

          {/* Idle */}
          {!isLoading && results === null && (
            <div className="glass-card p-12 rounded-2xl text-center border border-dashed border-white/10">
              <div className="w-16 h-16 rounded-2xl gradient-bg flex items-center justify-center mx-auto mb-4">
                <Sparkles className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold mb-2">AI-Powered Lead Generation</h3>
              <p className="text-muted-foreground max-w-sm mx-auto">
                Enter your skills and target client type — Gemini AI will generate 9 realistic Pakistani business leads with contact details.
              </p>
            </div>
          )}

          {/* Results */}
          {!isLoading && results && results.length > 0 && (
            <AnimatePresence>
              <div className="grid md:grid-cols-2 gap-4">
                {results.map((lead, i) => {
                  const isSaved = savedLeads.has(lead.id);
                  const waNumber = lead.phone.replace(/[^0-9]/g, "");
                  const waFormatted = waNumber.startsWith("0") ? "92" + waNumber.slice(1) : waNumber;
                  const mapsUrl = `https://www.google.com/maps/search/${encodeURIComponent(lead.name + " " + lead.address + " Pakistan")}`;

                  return (
                    <motion.div
                      key={lead.id}
                      initial={{ opacity: 0, y: 16, scale: 0.96 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      transition={{ delay: i * 0.07 }}
                      whileHover={{ y: -4 }}
                      className="glass-card p-5 rounded-xl flex flex-col hover:border-primary/40 transition-colors"
                      data-testid={`card-lead-${i}`}
                    >
                      {/* Header */}
                      <div className="flex justify-between items-start mb-3 gap-2">
                        <h4 className="font-bold text-base leading-snug" title={lead.name}>
                          {lead.name}
                        </h4>
                        <span className={`text-xs px-2 py-1 rounded-full border whitespace-nowrap shrink-0 font-semibold ${badgeStyles[lead.badge]}`}>
                          {lead.badge} Lead
                        </span>
                      </div>

                      {/* Details */}
                      <div className="space-y-1.5 mb-4 text-sm text-muted-foreground flex-1">
                        <p className="flex items-start gap-2">
                          <MapPin className="w-3.5 h-3.5 shrink-0 mt-0.5 text-primary/70" />
                          <span className="line-clamp-2">{lead.address}</span>
                        </p>
                        <p className="flex items-center gap-2">
                          <Phone className="w-3.5 h-3.5 shrink-0 text-primary/70" />
                          {lead.phone}
                        </p>
                        {lead.website && (
                          <p className="flex items-center gap-2">
                            <Globe className="w-3.5 h-3.5 shrink-0 text-primary/70" />
                            <span className="truncate">{lead.website}</span>
                          </p>
                        )}
                        <p className="text-xs italic text-muted-foreground/70 pt-0.5">
                          "{lead.reason}"
                        </p>
                      </div>

                      {/* Score bar */}
                      <div className="mb-4">
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-muted-foreground">Match Score</span>
                          <span className="font-bold">{lead.score}%</span>
                        </div>
                        <div className="h-1.5 bg-black/50 rounded-full overflow-hidden">
                          <motion.div
                            className="h-full rounded-full"
                            initial={{ width: 0 }}
                            animate={{ width: `${lead.score}%` }}
                            transition={{ delay: i * 0.07 + 0.3, duration: 0.7, ease: "easeOut" }}
                            style={{ backgroundColor: scoreColor[lead.badge] }}
                          />
                        </div>
                      </div>

                      {/* Action buttons */}
                      <div className="flex flex-col gap-2 mt-auto">
                        <div className="grid grid-cols-2 gap-2">
                          <a
                            href={`https://wa.me/${waFormatted}?text=Hi, I came across ${lead.name} and would love to discuss how I can help your business`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-[#25D366]/20 hover:bg-[#25D366]/30 text-[#25D366] border border-[#25D366]/50 py-2 rounded-lg text-sm font-semibold flex items-center justify-center gap-1.5 transition-colors"
                            data-testid={`button-whatsapp-${i}`}
                          >
                            <SiWhatsapp className="w-4 h-4" /> WhatsApp
                          </a>
                          <a
                            href={mapsUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-blue-500/20 hover:bg-blue-500/30 text-blue-400 border border-blue-500/50 py-2 rounded-lg text-sm font-semibold flex items-center justify-center gap-1.5 transition-colors"
                            data-testid={`button-maps-${i}`}
                          >
                            <ExternalLink className="w-4 h-4" /> Maps
                          </a>
                        </div>
                        <button
                          onClick={() => toggleSave(lead.id, lead.name)}
                          className={`w-full py-2 rounded-lg text-sm font-semibold flex items-center justify-center gap-2 transition-all ${
                            isSaved
                              ? "bg-primary/20 text-primary border border-primary/50"
                              : "bg-white/5 hover:bg-white/10 text-white border border-white/10"
                          }`}
                          data-testid={`button-save-${i}`}
                        >
                          {isSaved ? "✓ Lead Saved" : "Save Lead"}
                        </button>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </AnimatePresence>
          )}
        </div>
      </div>
    </motion.div>
  );
}
